config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  get 'dashboard/properties'
  get 'dashboard/reports'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  resources :properties
  devise_for :accounts
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable

  has_many :properties

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
  has_one_attached :photo
  belongs_to :account

  scope :latest, -> { order created_at: :desc }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_perameters, if: :devise_controller?

  protected

  def configure_permitted_perameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:update, keys: [:first_name, :last_name, :url])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_account!, only: %i[index]
  before_action :set_sidebar

  def index
  end

  def properties
  end

  def reports
  end

  private

  def set_sidebar
    @show_sidebar = true
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @title = 'Home'
    @properties = Property.latest
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[show edit update destroy]
  before_action :authenticate_account!, only: %i[new create edit update destroy]
  before_action :set_sidebar, except: [:show]

  # GET /properties or /properties.json
  def index
    @title = 'All Properties'
    @properties = Property.paginate(page: params[:page], per_page: 10)
  end

  # GET /properties/1 or /properties/1.json
  def show
    @agent = @property.account
    @title = @property.name
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit; end

  # POST /properties or /properties.json
  def create
    @property = Property.new(property_params)
    @property.account_id = current_account.id
    save_and_show_property
  end

  def save_and_show_property
    respond_to do |format|
      if @property.save
        PropertyJob.set(wait: 15.seconds).perform_later(@property, current_account)
        format.html { redirect_to properties_path, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @id = @property.id
    @property.destroy
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_property
    @property = Property.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def property_params
    params.require(:property).permit(:name, :address, :price, :rooms, :bathrooms, :photo)
  end

  def set_sidebar
    @show_sidebar = true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
  def property_thumbnail(property)
    img = property.photo.present? ? property.photo : 'placeholder.png'
    image_tag img, class: 'property-thumb'
  end

  def property_photo_url(property)
    property.photo.present? ? main_app.url_for(property.photo) : 'placeholder.png'
  end

  def show_image_if_present(property)
    if property.photo.record.id.present?
      img = property.photo
      image_tag img, width: '500'
    end
  end
end

app/views/dashboard/index.html.erb
<div style="position: absolute; inset: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
</div>

app/views/dashboard/properties.html.erb
<h1>Dashboard#properties</h1>
<p>Find me in app/views/dashboard/properties.html.erb</p>

app/views/dashboard/reports.html.erb
<h1>Dashboard#reports</h1>
<p>Find me in app/views/dashboard/reports.html.erb</p>

app/views/home/index.html.erb
<main role="main">

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron" style="background-image:url('<%= image_path('dha-lahore.jpg') %>')">
        <div class="photo-overlay">
            <div class="container">
                <h1 class="display-3">Search for your new home today...</h1>
                <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
                <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more »</a></p>
            </div>
        </div>
    </div>

    <section id="latest-properties">
        <div class="container">
            <div class="row">
                <%= render 'properties/latest_properties' %>
            </div>
        </div>
    </section>

</main>

app/views/layouts/_footer.html.erb
<footer class="container">
    <p>&copy PropertyFinder 2021</p>
</footer>

app/views/layouts/_validation.html.erb
 <% if item.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

    <ul>
    <% item.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
    </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= @title %> - Property Finder </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body id="<%= controller.controller_name %>" class="<%= controller.action_name %> <%= "show-sidebar" if @show_sidebar.present? %>">
  
    <%# <% if ['home', 'devise', 'sessions', 'registrations'].include?(controller.controller_name) %>
    <% if @show_sidebar.nil? %>
      <header>
        <%= render 'layouts/nav/public' %>
        <%= yield %>
      </header>
    <% else %>
      <%= render 'layouts/nav/dashboard' %>
      <div class="container-fluid">
        <div class="row">
          <%= render 'layouts/nav/sidebar' %>
          <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
            <%= yield %>
          </main>
        </div>  
      </div>  
    <% end %>

    <div class="alert alert-info" role="alert">
      <%= notice %>
    </div>
    <div class="alert alert-info" role="alert">
      <%= alert %>
    </div>


    <%# <%= render 'layouts/footer' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
    <script>feather.replace()</script>
  </body>
</html>

app/views/layouts/nav/_dashboard.html.erb
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
  <%= link_to 'Property finder', dashboard_index_path, class:"navbar-brand col-sm-3 col-md-2 mr-0" %>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <% if account_signed_in? %>
        <%= link_to 'Logout', destroy_account_session_path, method: :delete, class:"nav-link"  %>
      <% else %>
        <%= link_to 'Log In', new_account_session_path, class:"nav-link" %>
      <% end %>
    </li>
  </ul>
</nav>

app/views/layouts/nav/_public.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="/">Property Finder</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <% if account_signed_in? %>
          <%= link_to 'Dashboard', dashboard_index_path, class:"nav-link" %>
        <% else %>
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        <% end %>
      </li>
      
      <li class="nav-item">
        <a class="nav-link" href="#latest-properties">Latest</a>
      </li>

    
      <% if account_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Logout', destroy_account_session_path, method: :delete, class:"nav-link" %>
        </li>
      <% else %>
      <li class="nav-item">
        <%= link_to 'Log In', new_account_session_path, class:"nav-link" %>
      </li>

      <li class="nav-item">
          <%= link_to 'Sign Up', new_account_registration_path, class:"nav-link" %>
      </li>
    <% end %>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/nav/_sidebar.html.erb
 <nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">
                <%= link_to dashboard_index_path, class:"nav-link" do %>
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                    Dashboard <span class="sr-only">(current)</span>
                <% end %>
            </li>

            <li class="nav-item">
                <%= link_to properties_path, class:"nav-link" do %>
                    <i data-feather="home"></i>
                    Properties
                <% end %>
            </li>

            <li class="nav-item">
                <%= link_to root_path, class:"nav-link" do %>
                    <i data-feather="layout"></i>
                    User Home
                <% end %>
            </li>

        </ul>
    </div>
</nav>

app/views/properties/_agent_details.html.erb
<strong class="d-inline-block mb-2 text-success">Agent Details</strong>

<h3 class="mb-0">
    <%= @agent.full_name %>
</h3>

<div class="mb-1 text-muted">
    Email: <%= @agent.email %>
</div>

<p class="card-text mb-auto">
    Link: <%= @agent.url %>
</p>

<a href="#">
    Contact Agent
</a>

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
  <%= render 'layouts/validation', item: @property %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :rooms %>
    <%= form.number_field :rooms, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :bathrooms %>
    <%= form.number_field :bathrooms, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :photo %>
    <%= form.file_field :photo, class:"form-control" %>
  </div>

  <%= show_image_if_present(property) %>
  

  <div class="actions">
    <%= form.submit "Save", class:"btn btn-success" %>
  </div>
<% end %>

app/views/properties/_latest_properties.html.erb
<% @properties.each do |property| %>
    <div class="col-md-4">
        <%= property_thumbnail(property) %>
        <h2> <%= property.name %> </h2>
        <p>
            <%= link_to 'View Detail', property_path(property), class:"btn btn-info" %>
        </p>
    </div>
<% end %>

app/views/properties/destroy.js.erb
$('#<%= @id %>').remove();

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Properties</h1>

<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Price</th>
        <th>Rooms</th>
        <th>Bathrooms</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @properties.each do |property| %>
        <tr id="<%= property.id %>">
          <td><%= property.name %></td>
          <td><%= property.address %></td>
          <td><%= property.price %></td>
          <td><%= property.rooms %></td>
          <td><%= property.bathrooms %></td>
          <td><%= link_to 'Show', property, class:"btn btn-info" %></td>
          <td><%= link_to 'Edit', edit_property_path(property), class:"btn btn-warning" %></td>
          <td>
              <p class="destroy-property btn btn-danger">
                Destroy
              </p>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="digg_pagination">
    <%= will_paginate @properties %>
  </div>
</div>
<br>

<%= link_to 'New Property', new_property_path, class:"btn btn-primary" %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path, class:"btn btn-primary mt-2" %>

app/views/properties/show.html.erb
<div class="bg-dark mt-5 property-main-photo" style="background-image:url('<%= property_photo_url(@property) %>')">
  <div class="col-md-12 photo-overlay">
  </div>
</div>

<div class="row m-2 p-2">
  <div class="col-md-6">
    <div class="card flex-md-row mb-4 box-shadow h-md-250">
      <div class="card-body d-flex flex-column align-items-start">
        <strong class="d-inline-block mb-2 text-primary">Property Details</strong>
        <h3 class="mb-0">
            <%= @property.name %>
        </h3>
        
        <div class="mb-1 text-muted">
          <%= @property.created_at %>
        </div>
        
        <p class="card-text mb-auto">
          Location: <%= @property.address %>
        </p>
        
        <p class="card-text mb-auto">
          Price: <%= @property.price %>
        </p>
        
        <p class="card-text mb-auto">
          Rooms: <%= @property.rooms %>
        </p>

        <p class="card-text mb-auto">
          Bathrooms: <%= @property.bathrooms %>
        </p>

        <a href="#">Contact Via Us</a>
      
      </div>
       <%= image_tag(@property.photo, class:"card-img-right flex-auto d-none d-md-block", alt:"Thumbnail [200x250]", style:"width: 250px; height: 250px;" ) %>
    </div>
  </div>

  <div class="col-md-6">
    <div class="card flex-md-row mb-4 box-shadow h-md-250">
      <div class="card-body d-flex flex-column align-items-start">
        <%= render 'properties/agent_details' %>
      </div>
      <%= image_tag asset_path('login_user.png'), class:"card-img-right flex-auto d-none d-md-block", style:"width: 250px; height: 250px;" %>
    </div>
  </div>
</div>